import { Collections, EnvironmentConfig, logger, Service } from '@microrealestate/common';
import { fileURLToPath } from 'url';
import i18n from 'i18n';
import migratedb from '../scripts/migration.js';
import path from 'path';
import { restoreDB } from '../scripts/dbbackup.js';
import routes from './routes.js';
import { checkAndCreateAdjustments } from './managers/indexadjustmentmanager.js';
import { generateMonthlyChargesAuto } from './managers/monthlybillingmanager.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

i18n.configure({
  locales: ['en', 'fr-FR', 'pt-BR', 'de-DE', 'es-CO'],
  directory: path.join(__dirname, 'locales'),
  updateFiles: false
});

async function onStartUp(application) {
  const { RESTORE_DB } = Service.getInstance().envConfig.getValues();
  if (RESTORE_DB) {
    logger.debug('restoring database from backup');
    await restoreDB();
    logger.debug('database restored');
  }

  // migrate db to the new models
  await migratedb();

  application.use(routes());

  // Agenda jobs periódicos via setInterval
  _scheduleDailyJobs();
}

function _msUntilNextHour(hour, minute = 0) {
  const now = new Date();
  const next = new Date(now);
  next.setHours(hour, minute, 0, 0);
  if (next <= now) next.setDate(next.getDate() + 1);
  return next - now;
}

function _scheduleDailyJobs() {
  async function runCharges() {
    try {
      const realms = await Collections.Realm.find().lean();
      const today = new Date();
      if (today.getDate() === 1) {
        for (const realm of realms) await generateMonthlyChargesAuto(String(realm._id));
        logger.info('Monthly charges generated by scheduled job');
      }
    } catch (err) {
      logger.error('Scheduled charges error:', err.message);
    }
  }

  async function runAdjustments() {
    try {
      const realms = await Collections.Realm.find().lean();
      for (const realm of realms) await checkAndCreateAdjustments(String(realm._id));
      logger.info('Index adjustments checked by scheduled job');
    } catch (err) {
      logger.error('Scheduled adjustments error:', err.message);
    }
  }

  const MS_24H = 24 * 60 * 60 * 1000;
  setTimeout(() => {
    runCharges();
    setInterval(runCharges, MS_24H);
  }, _msUntilNextHour(6));

  setTimeout(() => {
    runAdjustments();
    setInterval(runAdjustments, MS_24H);
  }, _msUntilNextHour(8));
}

async function Main() {
  let service;
  try {
    service = Service.getInstance(
      new EnvironmentConfig({
        DEMO_MODE: process.env.DEMO_MODE
          ? process.env.DEMO_MODE.toLowerCase() === 'true'
          : undefined,
        RESTORE_DB: process.env.RESTORE_DB
          ? process.env.RESTORE_DB.toLowerCase() === 'true'
          : undefined,
        EMAILER_URL: process.env.EMAILER_URL || 'http://localhost:8083/emailer',
        PDFGENERATOR_URL:
          process.env.PDFGENERATOR_URL || 'http://localhost:8082/pdfgenerator'
      })
    );

    await service.init({
      name: 'api',
      useMongo: true,
      useAxios: true,
      onStartUp
    });
    await service.startUp();
  } catch (err) {
    logger.error(err);
    service.shutdown(1);
  }
}

Main();
